/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0YqkmNT8UZK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import Image from "next/image";
import SubmitButton from "../ui/submitButton";
import PreOrderButton from "../ui/preOrderButton";

export function Component() {
	return (
		<div className="flex min-h-screen flex-col bg-background">
			<header className="sticky top-0 z-40 w-full border-b bg-background">
				<div className="container flex h-16 items-center justify-between px-4 md:px-6">
					<Link
						href="#"
						className="flex items-center gap-2"
						prefetch={false}>
						<Image
							src="/pastel_logo_transparent.png"
							alt="pastel Logo"
							width={64}
							height={64}
						/>
						{/* <CakeIcon className="h-6 w-6" /> */}
						<span className="text-2xl font-semibold">
							Pastel
							<span className="text-sm font-normal hidden sm:block">
								{" "}
								byPalak
								<span className="text-lg font-semibold">&</span>
								Preksha
							</span>
						</span>
					</Link>
					<nav className="hidden items-center gap-6 text-sm font-medium md:flex">
						<Link
							href="#menu"
							className="hover:underline"
							prefetch={false}>
							Menu
						</Link>
						<Link
							href="#about"
							className="hover:underline"
							prefetch={false}>
							About
						</Link>
						<Link
							href="#contact"
							className="hover:underline"
							prefetch={false}>
							Contact
						</Link>
					</nav>
					<PreOrderButton text="Pre-Order Now" size="sm"></PreOrderButton>
				</div>
			</header>
			<main className="flex-1">
				<section className="bg-muted py-12 md:py-24">
					<div className="container flex flex-col items-center gap-6 px-4 md:px-6 lg:flex-row lg:items-start lg:gap-12">
						<div className="flex-1 space-y-4 text-center lg:text-left">
							<h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
								Artisanal Baked Goods, Delivered to Your Door
							</h1>
							<p className="text-muted-foreground md:text-lg">
								Indulge in the finest baked treats, handcrafted
								with love and made-to-order just for you.
							</p>
							<PreOrderButton text="Pre-Order Via WhatsApp" size="lg"></PreOrderButton>
						</div>
						<Image
							src="/leafCake.jpg"
							width={600}
							height={400}
							alt="Bakery Treats"
							className="aspect-video w-full max-w-md rounded-lg object-cover"
						/>
					</div>
				</section>
				<section id="menu" className="py-12 md:py-24">
					<div className="container px-4 md:px-6">
						<div className="space-y-6 text-center">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
								Our Delectable Menu
							</h2>
							<p className="text-muted-foreground md:text-lg">
								Explore our selection of freshly baked goods,
								made with the finest ingredients.
							</p>
						</div>
						<div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
							<Card className="group">
								<CardHeader>
									<img
										src="/leafCake.jpg"
										width={400}
										height={300}
										alt="Croissant"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Dreamy Vanilla Buttercream Cake
									</h3>
									<p className="text-muted-foreground">
										Flaky, golden-brown croissants made with
										premium butter and a touch of sweetness.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$3.50 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
							<Card className="group">
								<CardHeader>
									<img
										src="/ButterCreamCupcakes.jpg"
										width={400}
										height={300}
										alt="Cinnamon Rolls"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Buttercream Cupcakes
									</h3>
									<p className="text-muted-foreground">
										Warm, gooey cinnamon rolls topped with a
										sweet cream cheese frosting.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$4.25 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
							<Card className="group">
								<CardHeader>
									<img
										src="/AlmondSpongeCake.jpg"
										width={400}
										height={300}
										alt="Chocolate Chip Cookies"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Honey Almond Sponge Cake
									</h3>
									<p className="text-muted-foreground">
										Soft, chewy cookies loaded with melty
										chocolate chips.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$2.75 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
							<Card className="group">
								<CardHeader>
									<img
										src="/StrawberrySpongeCake.jpg"
										width={400}
										height={300}
										alt="Lemon Bars"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Vanilla Strawberry Sponge Cake
									</h3>
									<p className="text-muted-foreground">
										Fresh homemade strawberry compote.
										Vanilla whipped with hints of
										strawberry.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$3.25 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
							<Card className="group">
								<CardHeader>
									<img
										src="/diwaliHampers.jpg"
										width={400}
										height={300}
										alt="Blueberry Muffins"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Special Diwali hampers
									</h3>
									<p className="text-muted-foreground">
										Fluffy muffins bursting with juicy
										blueberries.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$3.75 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
							<Card className="group">
								<CardHeader>
									<img
										src="/Chocolate.jpg"
										width={400}
										height={300}
										alt="Assorted Macarons"
										className="aspect-video w-full rounded-t-lg object-cover transition-all group-hover:scale-105"
									/>
								</CardHeader>
								<CardContent className="space-y-2">
									<h3 className="text-xl font-semibold">
										Cranberry fusion chocolate bars
									</h3>
									<p className="text-muted-foreground">
										A colorful assortment of delicate,
										flavored macarons.
									</p>
									<div className="flex items-center justify-between">
										<span className="font-medium">
											$2.00 each
										</span>
										<PreOrderButton text="Pre-Order Via WhatsApp" size="sm">
											Pre-Order Via WhatsApp
										</PreOrderButton>
									</div>
								</CardContent>
							</Card>
						</div>
					</div>
				</section>
				<section id="about" className="bg-muted py-12 md:py-24">
					<div className="container flex flex-col items-center gap-6 px-4 md:px-6 lg:flex-row lg:items-start lg:gap-12">
						<Image
							src="/AboutImg.jpg"
							width={600}
							height={400}
							alt="Bakery Interior"
							className="aspect-video w-full max-w-md rounded-lg object-cover"
						/>
						<div className="flex-1 space-y-4 text-center lg:text-left">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
								About Our Bakery
							</h2>
							<p className="text-muted-foreground md:text-lg">
								Pastel is a family-owned bakery that has been
								delighting customers with our handcrafted baked
								goods. We use only the finest, locally-sourced
								ingredients to create our delectable treats,
								ensuring each one is a true work of art.
							</p>
							<p className="text-muted-foreground md:text-lg">
								Our passion for baking is evident in every bite,
								and we take great pride in providing our
								customers with an exceptional experience.
								Whether you're craving a flaky croissant, a rich
								chocolate chip cookie, or a delicate macaron,
								we're confident you'll find something to love in
								our menu.
							</p>
						</div>
					</div>
				</section>
				<section id="contact" className="py-12 md:py-24">
					<div className="container px-4 md:px-6">
						<div className="space-y-6 text-center">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
								Get in Touch
							</h2>
							<p className="text-muted-foreground md:text-lg">
								Have a special request or need more information?
								Fill out the form below and we'll be in touch.
							</p>
						</div>
						<form className="mx-auto mt-12 max-w-md space-y-4">
							<Input
								type="text"
								placeholder="Name"
								className="w-full"
								name="name"
							/>
							<Input
								type="email"
								placeholder="Email"
								className="w-full"
								name="email"
							/>
							<Textarea
								placeholder="Message"
								className="w-full"
								name="message"
							/>

							<SubmitButton />
						</form>
					</div>
				</section>
			</main>
			<footer className="bg-muted py-6 text-center text-sm text-muted-foreground">
				<div className="container px-4 md:px-6">
					&copy; 2024 Pastel. All rights reserved.
				</div>
			</footer>
		</div>
	);
}

function CakeIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round">
			<path d="M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8" />
			<path d="M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1" />
			<path d="M2 21h20" />
			<path d="M7 8v3" />
			<path d="M12 8v3" />
			<path d="M17 8v3" />
			<path d="M7 4h0.01" />
			<path d="M12 4h0.01" />
			<path d="M17 4h0.01" />
		</svg>
	);
}

function XIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round">
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}
